#!/bin/bash

apt-get update

apt-get install -y nginx

echo "
server {
    listen 80;
    root /var/www/html;
    index index.html index.htm;

    location / {
        try_files \$uri \$uri/ /index.html;
    }
}
" > /etc/nginx/sites-available/default

echo "Hello World!" > /var/www/html/index.html

/etc/init.d/nginx restart

